/**
 * `components/index.js` exists simply as a 'central export' for our components.
 * This way, we can import all of our components from the same place, rather than
 * having to figure out which file they belong to!
 */
export {default as Navbar} from './navbar'
export {default as LoginForm} from './Login.js'
export {default as SignupForm} from './Signup.js'
export {default as NavBar} from './navbar'
export {default as Chat} from './Chat'
export {default as Home} from './Home'
export {default as Announcements} from './Announcements'
export {default as Assignments} from './Assignments'
export {default as MakeAssignment} from './MakeAssignment'
export {default as TableAssignments} from './TableAssignments'
export {default as Sidebar} from './Sidebar'
export {default as Students} from './Students'
export {default as Profile} from './Profile'
export {default as Lessons} from './Lessons'
export {default as ManageAssignments} from './ManageAssignments'
export {default as Grades} from './Grades'
export {default as WhiteBoard} from './WhiteBoard'
export {default as Live} from './Live'
export {default as Verification} from './Verification'
export {default as OneStudentGrades} from './OneStudentGrades'
export {default as TeacherGrades} from './TeacherGrades'
export {default as TeacherGrading} from './TeacherGrading'
export {default as Video2} from './video/Video2'
export {default as UploadExcel} from './UploadExcel'
export {default as TestStudent} from './TestStudent'
//export {default as TestTeacher} from './test/TestTeacher'
export {default as WBconstants} from './WBmodules/WBconstants'
export {default as ReportCard} from './ReportCard'
